### ISSUE TITLE
`toTask`

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts-rxjs#15]
`Observable`s already have a built in method `toPromise`. However, in fp-ts, `Task` is preferred over `Promise`. Therefore I would like to suggest adding a `toTask` helper:

```ts
export const toTask = <V>(ob$: RxJS.Observable<V>): T.Task<V> => () => ob$.toPromise();
```

**Comment by mlegenhausen** [comment]
See #21
