### ISSUE TITLE
Add `chainW`

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts-rxjs#37]
This was recently added to types in fp-ts. It would be great to add it to `Observable` and `ObservableEither`.

**Comment by anthonyjoeseph** [comment]
Here's a quick copy-paste implementation until this issue gets a proper PR:

```ts
export const chainW = <E, A, B>(
  f: (a: A) => OBE.ObservableEither<E, B>
) => <D>(ma: OBE.ObservableEither<D, A>): OBE.ObservableEither<D | E, B> =>
  OBE.chain(f)(ma as any)
```
