### ISSUE TITLE
Add `liftEither` for `ObservableEither`

### ISSUE THREAD

**Issue by agabriele-radius** [gcanti/fp-ts-rxjs#38]
I often end up needing a way to use [MonoTypeOperatorFunction](https://github.com/ReactiveX/rxjs/blob/master/src/internal/types.ts#L35)'s on the `right` case of `ObservableEither`'s

E.g. [filter](https://www.learnrxjs.io/learn-rxjs/operators/filtering/filter) or [takeUntil](https://www.learnrxjs.io/learn-rxjs/operators/filtering/takeuntil) for `ObservableEither`

```
export const liftEither = <E, A, B>(
  f: (a: r.Observable<A>) => r.Observable<B>
): ((a: OBE.ObservableEither<E, A>) => OBE.ObservableEither<E, B>) =>
  flow(
    OB.separate,
    ({left, right}: {left: r.Observable<Err>; right: r.Observable<A>}) =>
      r.merge(pipe(left, ro.map(E.left)), pipe(right, f, ro.map(E.right)))
  )
```

I can make a P.R. if desired, but I'm not sure if this is the best way to do this.

**Comment by anthonyjoeseph** [comment]
whoops wrong github acct
