### ISSUE TITLE
Imports are not rewritten

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts-rxjs#50]
### Current Behavior

Modules in the `es6` folder refer to `fp-ts/lib/*` and thus do not tree shake properly.

### Expected behavior

Modules in the `es6` folder refer to `fp-ts/es6/*`

### Reproducible example

See imports at top of https://unpkg.com/fp-ts-rxjs@0.6.12/es6/Observable.js

### Additional context

This appears to be a regression from https://github.com/gcanti/fp-ts-rxjs/commit/d490d8ccee761f48d624e5e86ad19b0f8729c546.

It was working in 0.6.11: https://unpkg.com/fp-ts-rxjs@0.6.11/es6/Observable.js

**Comment by gcanti** [comment]
@OliverJAsh opss, forgot to update `import-path-rewrite` before publishing, thanks for the bug report, will fix asap

**Comment by gcanti** [comment]
@OliverJAsh patch released
